language: c
sudo: false 
script:
  - g++ -fprofile-arcs -ftest-coverage test.cpp filestuff.cpp mixing.cpp inputhandler.cpp -o test -lm
  - ./test
  - gcov filestuff.cpp -r
  - gcov mixing.cpp -r
  - gcov inputhandler.cpp -r

after_success:
  - bash <(curl -s https://codecov.io/bash)
